# -*- mode: ruby -*-
# vi: set ft=ruby :

$minikube = <<SCRIPT
if [[ ! -f ~/.okanstack.sh ]]; then
    wget -q https://raw.githubusercontent.com/rajalokan/okanstack/master/okanstack.sh -O ~/.okanstack.sh
fi
source ~/.okanstack.sh
ostack_configure_hosts minikube
ostack_bootstrap minikube
SCRIPT

$minikubedev = <<SCRIPT
if [[ ! -f ~/.okanstack.sh ]]; then
    wget -q https://raw.githubusercontent.com/rajalokan/okanstack/master/okanstack.sh -O ~/.okanstack.sh
fi
source ~/.okanstack.sh && ostack_install go
sudo apt install -y gcc pkg-config libvirt-dev
SCRIPT


Vagrant.configure("2") do |config|
    config.vm.hostname = "minikube"
    config.vm.box = "bento/ubuntu-18.04"
	config.vm.synced_folder "../minikube", "/opt/minikube"
    config.vm.provider :virtualbox do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    end
    #config.vm.provision "shell", inline: $minikube, privileged: false
    #config.vm.provision "shell", inline: $minikubedev, privileged: false
end
