# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION=2

Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    config.vm.provision :shell do |shell|
        shell.path = "~/.vagrant.d/bootstrap.sh"
        shell.args = "#{ENV['HOST_IP']}"
    end
end
