name: Deploy To Prod
on:
  release:
    types: [published]
    
jobs:
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to QA
        run: echo Deploying ${GITHUB_SHA} to QA (release ${GITHUB_REF})

  deploy-prod:
    name: Deploy to Production
    needs: [deploy-qa]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Production
        run: echo Deploying ${GITHUB_SHA} to Production (release ${GITHUB_REF})        
