name: Deploy To Prod
on:
  workflow_dispatch:
    inputs:
      ansible-playbook:
        description: Github commit hash to deploy
        required: true
    
jobs:
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to QA
        run: echo Deploying ${GITHUB_SHA} to QA for release ${{ github.event.release.tag_name }}

  deploy-prod:
    name: Deploy to Production
    needs: [deploy-qa]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Production
        run: echo Deploying ${GITHUB_SHA} to Production for release ${{ github.event.release.tag_name }}
