name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build & Push 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Building
        run: echo Building ${GITHUB_SHA::6}

      - name: Pushing
        run: echo Pushing ${GITHUB_SHA::6}

  deploy-staging:
    name: Deploy to Staging
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to staging
        run: echo Deploying to Staging
