name: Deploy To Prod - ${{ github.event.inputs.release-tag }}
on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: Github commit hash to deploy
        required: true
      release-tag:
        description: Semver release tag
        required: true

jobs:
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to QA
        run: echo Deploying ${{ github.event.inputs.commit-hash }} to QA

  deploy-prod:
    name: Deploy to Production
    needs: [deploy-qa]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://rajalokan.com
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Production
        run: echo Deploying ${{ github.event.inputs.commit-hash }} to Production
